### ISSUE TITLE
Compat with Quark's inventory sorting

### ISSUE THREAD

**Issue by mxnmnm** [canitzp/FixableSlots#1]
Whenever I lock a slot with an item and I sort with quark, it can get overridden by whatever quark wants to be in that slot. It would be nice to sort my inventory with those slots being ignored.

**Comment by canitzp** [comment]
I see the issue, but I'm not sure if it is fixable on my side

**Comment by canitzp** [comment]
It is most likely a problem with quark. It has to check "isItemValid" for the slot it wants to put the item in. Otherwise there is no way for me to prevent this faulty behavior

**Comment by mxnmnm** [comment]
I see :/ thanks for helping
