### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Taknax** [canitzp/FixableSlots#2]
I cant get it work. No matter in exact mode or not.

https://i.imgur.com/m5OTVBd.png

https://i.imgur.com/Sl7HPvm.png

https://i.imgur.com/vBl63tp.png

**Comment by canitzp** [comment]
Can you please tell me which version of Minecraft and of my mod you are using? Also the modpack name would be nice

**Comment by Taknax** [comment]
O sry. Ofc.
I am using Minecraft 1.12.2 and the new forge 14.23.5.2855. The FS modversion is 1.1.0. The modpack is atm not uploadet, but i tried without any other mod installed. Also just with FS the issue occure too.

**Comment by canitzp** [comment]
I'm sorry, but I can't help you with the 1.12.2 forge version anymore. A lot has changed since the last 1.12.2 release and since I can't find any documentation, I cannot fix it.

**Comment by Taknax** [comment]
O thats sad. Thank you for attention.
